# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-11-07 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set([('lat', 'lng')]),
        ),
    ]
